apiVersion: v1
kind: Service
metadata:
  name: irctc-service
spec:
  selector:
    app: irctc
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 32210
  type: NodePort
