apiVersion: apps/v1
kind: Deployment
metadata:
  name: irctc-deployment
  labels:
    app: irctc-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irctc-api
  template:
    metadata:
      labels:
        app: irctc-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: irctc-container
        image: manasabhagwat/irctc_test_api:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: irctc-service
  labels:
    app: irctc-api
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: irctc-api
